#!/usr/bin/env bash
# ProsperoPuzzles - Vendor Simon Tatham's Portable Puzzle Collection.
# Copyright (C) 2026 BlackBearReloaded
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copies the pinned upstream midend, shared libraries and the 40 official
# games into src/third_party/sgt-puzzles, unmodified, and regenerates the
# combined-build game list and the catalog metadata table.
#
# usage: tools/update-sgt-puzzles.sh [commit]

set -euo pipefail

root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
upstream=https://git.tartarus.org/simon/puzzles.git
commit=${1:-616da16f25da428ccda805536209095bd062676e}
checkout="$root/.deps/sgt-puzzles-src"
destination="$root/src/third_party/sgt-puzzles"
docs="$root/third_party/sgt-puzzles-docs"

if [[ ! -d $checkout/.git ]]; then
    git clone --quiet "$upstream" "$checkout"
fi
git -C "$checkout" fetch --quiet origin
git -C "$checkout" checkout --quiet --detach "$commit"
resolved=$(git -C "$checkout" rev-parse HEAD)

core=(combi.c divvy.c draw-poly.c drawing.c dsf.c findloop.c grid.c latin.c laydomino.c
    loopgen.c malloc.c matching.c midend.c misc.c penrose.c penrose-legacy.c printing.c
    ps.c random.c sort.c tdq.c tree234.c version.c hat.c spectre.c list.c)
headers=(puzzles.h grid.h latin.h loopgen.h matching.h penrose.h penrose-internal.h
    penrose-legacy.h hat.h hat-internal.h hat-tables.h spectre.h spectre-internal.h
    spectre-tables-auto.h spectre-tables-manual.h tree234.h version.h)

mapfile -t games < <(python3 - "$checkout/CMakeLists.txt" <<'PY'
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
names = sorted(set(re.findall(r"^puzzle\((\w+)", text, re.M)) - {"nullgame"})
print("\n".join(names))
PY
)
(( ${#games[@]} == 40 )) || { echo "expected 40 official games, found ${#games[@]}" >&2; exit 2; }

rm -rf -- "$destination"
mkdir -p "$destination" "$docs"
for file in "${core[@]}" "${headers[@]}"; do
    cp -- "$checkout/$file" "$destination/$file"
done
for game in "${games[@]}"; do
    cp -- "$checkout/$game.c" "$destination/$game.c"
done
for game in "${games[@]}"; do
    printf 'GAME(%s)\n' "$game"
done > "$destination/generated-games.h"
cp -- "$checkout/LICENCE" "$destination/LICENCE"
cp -- "$checkout/LICENCE" "$checkout/puzzles.but" "$checkout/README" "$docs/"
printf '%s\n%s\n' "$upstream" "$resolved" > "$destination/UPSTREAM"

# Local fixes to upstream, each documented in its patch header.
shopt -s nullglob
for patch_file in "$root"/patches/sgt/*.patch; do
    patch --quiet --forward -p1 -d "$destination" < "$patch_file"
    printf 'patched: %s\n' "${patch_file##*/}" >> "$destination/UPSTREAM"
done
shopt -u nullglob

# Catalog metadata (display name, description, objective) from upstream CMake.
python3 - "$checkout/CMakeLists.txt" "$root/src/games/sgt/upstream_meta.inc" "$resolved" <<'PY'
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
entries = []
for match in re.finditer(r"^puzzle\((\w+)(.*?)\)\s*$", text, re.M | re.S):
    name, body = match.group(1), match.group(2)
    if name == "nullgame":
        continue
    fields = {}
    for key in ("DISPLAYNAME", "DESCRIPTION", "OBJECTIVE"):
        found = re.search(key + r'\s+"((?:[^"\\]|\\.)*)"', body, re.S)
        value = found.group(1) if found else ""
        value = re.sub(r"\\\n\s*", "", value)
        fields[key] = " ".join(value.split())
    entries.append((name, fields))
entries.sort()
if len(entries) != 40:
    raise SystemExit(f"expected 40 metadata entries, found {len(entries)}")
def c_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
with open(sys.argv[2], "w", encoding="utf-8") as out:
    out.write("// ProsperoPuzzles - Generated by tools/update-sgt-puzzles.sh; do not edit.\n")
    out.write("// Copyright (C) 2026 BlackBearReloaded\n")
    out.write("// SPDX-License-Identifier: GPL-3.0-or-later\n")
    out.write(f"// Upstream commit {sys.argv[3]}; strings are from its CMakeLists.txt (MIT).\n\n")
    out.write("// SGT_GAME(id, display name, description, objective)\n")
    for name, fields in entries:
        out.write(f"SGT_GAME({name}, {c_string(fields['DISPLAYNAME'])},\n")
        out.write(f"         {c_string(fields['DESCRIPTION'])},\n")
        out.write(f"         {c_string(fields['OBJECTIVE'])})\n")
PY
printf 'Vendored %d games and %d core files from %s\n' "${#games[@]}" "${#core[@]}" "$resolved"
